name: Update Hugging Face Downloads

on:
  schedule:
    - cron: '0 0 * * 0'  # Runs every Sunday at midnight (00:00 UTC)
  workflow_dispatch:  # Allows manual triggering

jobs:
  update_downloads:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install huggingface_hub

      - name: Get Hugging Face Model Download Count (All-Time)
        run: |
          python -c "
from huggingface_hub import model_info
model = model_info('zhreyu/ComicStrips-Lora-Fluxdev', expand=['downloadsAllTime'])
with open('download_count.txt', 'w') as f:
    f.write(str(model.downloads_all_time))
          "

      - name: Update README.md with All-Time Downloads
        run: |
          DOWNLOADS=$(cat download_count.txt)
          # Find and update the download badge link with all-time downloads
          sed -i 's/https:\/\/img.shields.io\/badge\/downloads-[0-9]*-blue/https:\/\/img.shields.io\/badge\/downloads-'${DOWNLOADS}'-blue/' README.md

      - name: Commit changes
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'actions@github.com'
          git add README.md
          git commit -m "Update Hugging Face model downloads (All-Time)"
          git push
